packages:
  - app/vue
  - app/express
  - common/lib
  - common/prisma
  - docker

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - canvas
  - esbuild
  - msw
  - prisma
  - prisma-zod-generator

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  qs@<6.14.1: '>=6.14.1'
