packages:
  - app/vue
  - app/express
  - common/lib
  - common/prisma
  - docker

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - prisma

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
