packages:
  - apps/vue
  - apps/express
  - docker
  - packages/lib
  - packages/prisma

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
