version: "3"
services:
  database:
    container_name: todo-database
    image: postgres:14.3
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: todo
      POSTGRES_USER: todo
      POSTGRES_DB: todo_db
    restart: on-failure
    volumes:
      - todo-volume:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  todo-volume:
networks:
  todo-network:
    external: true
