/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyBreadcrumb: typeof import('./component/navi/MyBreadcrumb.vue')['default']
    MyButton: typeof import('./component/button/MyButton.tsx')['default']
    MyCheckbox: typeof import('./component/input/MyCheckbox.vue')['default']
    MyDownloadFileList: typeof import('./component/MyDownloadFileList.vue')['default']
    MyDropdown: typeof import('./component/MyDropdown.vue')['default']
    MyInput: typeof import('./component/input/MyInput.vue')['default']
    MyInputPassword: typeof import('./component/input/MyInputPassword.vue')['default']
    MyModalInputFile: typeof import('./component/input/MyModalInputFile.vue')['default']
    MySelect: typeof import('./component/input/MySelect.vue')['default']
    MySortButton: typeof import('./component/MySortButton.vue')['default']
    MyTextarea: typeof import('./component/input/MyTextarea.vue')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const MyBreadcrumb: typeof import('./component/navi/MyBreadcrumb.vue')['default']
  const MyButton: typeof import('./component/button/MyButton.tsx')['default']
  const MyCheckbox: typeof import('./component/input/MyCheckbox.vue')['default']
  const MyDownloadFileList: typeof import('./component/MyDownloadFileList.vue')['default']
  const MyDropdown: typeof import('./component/MyDropdown.vue')['default']
  const MyInput: typeof import('./component/input/MyInput.vue')['default']
  const MyInputPassword: typeof import('./component/input/MyInputPassword.vue')['default']
  const MyModalInputFile: typeof import('./component/input/MyModalInputFile.vue')['default']
  const MySelect: typeof import('./component/input/MySelect.vue')['default']
  const MySortButton: typeof import('./component/MySortButton.vue')['default']
  const MyTextarea: typeof import('./component/input/MyTextarea.vue')['default']
  const OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}