/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/signin': RouteRecordInfo<
      '/(auth)/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/signup': RouteRecordInfo<
      '/(auth)/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//mypage'
      | '//mypage/'
      | '//mypage/account'
      | '//mypage/change-password'
      | '//mypage/notification'
      | '//mypage/security'
      | '//space'
      | '//space/'
      | '//space/[space_id]'
      | '//space/[space_id]/'
      | '//space/[space_id]/board'
      | '//space/[space_id]/calendar'
      | '//space/[space_id]/chat'
      | '//space/[space_id]/drive'
      | '//space/[space_id]/list'
      | '//space/[space_id]/setting'
      | '//space/[space_id]/setting/'
      | '//space/[space_id]/setting/chat'
      | '//space/[space_id]/table'
      | '//space/[space_id]/table/'
      | '//space/[space_id]/table/[todo_id]'
      | '//space/[space_id]/table/add'
      | '//space/[space_id]/whiteboard'
    >,
    '//mypage': RouteRecordInfo<
      '//mypage',
      '/mypage',
      Record<never, never>,
      Record<never, never>,
      | '//mypage/'
      | '//mypage/account'
      | '//mypage/change-password'
      | '//mypage/notification'
      | '//mypage/security'
    >,
    '//mypage/': RouteRecordInfo<
      '//mypage/',
      '/mypage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//mypage/account': RouteRecordInfo<
      '//mypage/account',
      '/mypage/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//mypage/change-password': RouteRecordInfo<
      '//mypage/change-password',
      '/mypage/change-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//mypage/notification': RouteRecordInfo<
      '//mypage/notification',
      '/mypage/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//mypage/security': RouteRecordInfo<
      '//mypage/security',
      '/mypage/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//space': RouteRecordInfo<
      '//space',
      '/space',
      Record<never, never>,
      Record<never, never>,
      | '//space/'
      | '//space/[space_id]'
      | '//space/[space_id]/'
      | '//space/[space_id]/board'
      | '//space/[space_id]/calendar'
      | '//space/[space_id]/chat'
      | '//space/[space_id]/drive'
      | '//space/[space_id]/list'
      | '//space/[space_id]/setting'
      | '//space/[space_id]/setting/'
      | '//space/[space_id]/setting/chat'
      | '//space/[space_id]/table'
      | '//space/[space_id]/table/'
      | '//space/[space_id]/table/[todo_id]'
      | '//space/[space_id]/table/add'
      | '//space/[space_id]/whiteboard'
    >,
    '//space/': RouteRecordInfo<
      '//space/',
      '/space',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//space/[space_id]': RouteRecordInfo<
      '//space/[space_id]',
      '/space/:space_id',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | '//space/[space_id]/'
      | '//space/[space_id]/board'
      | '//space/[space_id]/calendar'
      | '//space/[space_id]/chat'
      | '//space/[space_id]/drive'
      | '//space/[space_id]/list'
      | '//space/[space_id]/setting'
      | '//space/[space_id]/setting/'
      | '//space/[space_id]/setting/chat'
      | '//space/[space_id]/table'
      | '//space/[space_id]/table/'
      | '//space/[space_id]/table/[todo_id]'
      | '//space/[space_id]/table/add'
      | '//space/[space_id]/whiteboard'
    >,
    '//space/[space_id]/': RouteRecordInfo<
      '//space/[space_id]/',
      '/space/:space_id',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/board': RouteRecordInfo<
      '//space/[space_id]/board',
      '/space/:space_id/board',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/calendar': RouteRecordInfo<
      '//space/[space_id]/calendar',
      '/space/:space_id/calendar',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/chat': RouteRecordInfo<
      '//space/[space_id]/chat',
      '/space/:space_id/chat',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/drive': RouteRecordInfo<
      '//space/[space_id]/drive',
      '/space/:space_id/drive',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/list': RouteRecordInfo<
      '//space/[space_id]/list',
      '/space/:space_id/list',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/setting': RouteRecordInfo<
      '//space/[space_id]/setting',
      '/space/:space_id/setting',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | '//space/[space_id]/setting/'
      | '//space/[space_id]/setting/chat'
    >,
    '//space/[space_id]/setting/': RouteRecordInfo<
      '//space/[space_id]/setting/',
      '/space/:space_id/setting',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/setting/chat': RouteRecordInfo<
      '//space/[space_id]/setting/chat',
      '/space/:space_id/setting/chat',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/table': RouteRecordInfo<
      '//space/[space_id]/table',
      '/space/:space_id/table',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | '//space/[space_id]/table/'
      | '//space/[space_id]/table/[todo_id]'
      | '//space/[space_id]/table/add'
    >,
    '//space/[space_id]/table/': RouteRecordInfo<
      '//space/[space_id]/table/',
      '/space/:space_id/table',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/table/[todo_id]': RouteRecordInfo<
      '//space/[space_id]/table/[todo_id]',
      '/space/:space_id/table/:todo_id',
      { space_id: ParamValue<true>, todo_id: ParamValue<true> },
      { space_id: ParamValue<false>, todo_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/table/add': RouteRecordInfo<
      '//space/[space_id]/table/add',
      '/space/:space_id/table/add',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '//space/[space_id]/whiteboard': RouteRecordInfo<
      '//space/[space_id]/whiteboard',
      '/space/:space_id/whiteboard',
      { space_id: ParamValue<true> },
      { space_id: ParamValue<false> },
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/page/(auth)/signin.tsx': {
      routes:
        | '/(auth)/signin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/(auth)/signup.tsx': {
      routes:
        | '/(auth)/signup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index.tsx': {
      routes:
        | '/'
        | '//mypage'
        | '//mypage/'
        | '//mypage/account'
        | '//mypage/change-password'
        | '//mypage/notification'
        | '//mypage/security'
        | '//space'
        | '//space/'
        | '//space/[space_id]'
        | '//space/[space_id]/'
        | '//space/[space_id]/board'
        | '//space/[space_id]/calendar'
        | '//space/[space_id]/chat'
        | '//space/[space_id]/drive'
        | '//space/[space_id]/list'
        | '//space/[space_id]/setting'
        | '//space/[space_id]/setting/'
        | '//space/[space_id]/setting/chat'
        | '//space/[space_id]/table'
        | '//space/[space_id]/table/'
        | '//space/[space_id]/table/[todo_id]'
        | '//space/[space_id]/table/add'
        | '//space/[space_id]/whiteboard'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/page/index/mypage.tsx': {
      routes:
        | '//mypage'
        | '//mypage/'
        | '//mypage/account'
        | '//mypage/change-password'
        | '//mypage/notification'
        | '//mypage/security'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/page/index/mypage/index.tsx': {
      routes:
        | '//mypage/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/mypage/account.tsx': {
      routes:
        | '//mypage/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/mypage/change-password.tsx': {
      routes:
        | '//mypage/change-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/mypage/notification.tsx': {
      routes:
        | '//mypage/notification'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/mypage/security.tsx': {
      routes:
        | '//mypage/security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space.tsx': {
      routes:
        | '//space'
        | '//space/'
        | '//space/[space_id]'
        | '//space/[space_id]/'
        | '//space/[space_id]/board'
        | '//space/[space_id]/calendar'
        | '//space/[space_id]/chat'
        | '//space/[space_id]/drive'
        | '//space/[space_id]/list'
        | '//space/[space_id]/setting'
        | '//space/[space_id]/setting/'
        | '//space/[space_id]/setting/chat'
        | '//space/[space_id]/table'
        | '//space/[space_id]/table/'
        | '//space/[space_id]/table/[todo_id]'
        | '//space/[space_id]/table/add'
        | '//space/[space_id]/whiteboard'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/page/index/space/index.tsx': {
      routes:
        | '//space/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id].tsx': {
      routes:
        | '//space/[space_id]'
        | '//space/[space_id]/'
        | '//space/[space_id]/board'
        | '//space/[space_id]/calendar'
        | '//space/[space_id]/chat'
        | '//space/[space_id]/drive'
        | '//space/[space_id]/list'
        | '//space/[space_id]/setting'
        | '//space/[space_id]/setting/'
        | '//space/[space_id]/setting/chat'
        | '//space/[space_id]/table'
        | '//space/[space_id]/table/'
        | '//space/[space_id]/table/[todo_id]'
        | '//space/[space_id]/table/add'
        | '//space/[space_id]/whiteboard'
      views:
        | 'default'
      pathParamNames:
        | 'space_id'
    }
    'src/page/index/space/[space_id]/index.tsx': {
      routes:
        | '//space/[space_id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/board.tsx': {
      routes:
        | '//space/[space_id]/board'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/calendar.tsx': {
      routes:
        | '//space/[space_id]/calendar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/chat.tsx': {
      routes:
        | '//space/[space_id]/chat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/drive.tsx': {
      routes:
        | '//space/[space_id]/drive'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/list.tsx': {
      routes:
        | '//space/[space_id]/list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/setting.tsx': {
      routes:
        | '//space/[space_id]/setting'
        | '//space/[space_id]/setting/'
        | '//space/[space_id]/setting/chat'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/setting/index.tsx': {
      routes:
        | '//space/[space_id]/setting/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/setting/chat.tsx': {
      routes:
        | '//space/[space_id]/setting/chat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/table.tsx': {
      routes:
        | '//space/[space_id]/table'
        | '//space/[space_id]/table/'
        | '//space/[space_id]/table/[todo_id]'
        | '//space/[space_id]/table/add'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/table/index.tsx': {
      routes:
        | '//space/[space_id]/table/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/table/[todo_id].tsx': {
      routes:
        | '//space/[space_id]/table/[todo_id]'
      views:
        | never
      pathParamNames:
        | 'todo_id'
    }
    'src/page/index/space/[space_id]/table/add.tsx': {
      routes:
        | '//space/[space_id]/table/add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/index/space/[space_id]/whiteboard.tsx': {
      routes:
        | '//space/[space_id]/whiteboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/page/[...404].tsx': {
      routes:
        | '/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
