/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/categories": {
    get: operations["CategoriesController.getCategories"];
    post: operations["CategoriesController.postCategory"];
  };
  "/api/categories/{category_id}": {
    get: operations["CategoriesController.getCategory"];
    put: operations["CategoriesController.putCategory"];
    delete: operations["CategoriesController.deleteCategory"];
  };
  "/api/todos": {
    get: operations["TodosController.getTodos"];
    post: operations["TodosController.postTodo"];
  };
  "/api/todos/{todo_id}": {
    get: operations["TodosController.getTodo"];
    put: operations["TodosController.putTodo"];
    delete: operations["TodosController.deleteTodo"];
  };
  "/api/todos/{todo_id}/done": {
    patch: operations["TodosController.patchTodoDone"];
  };
  "/api/todos/priority": {
    patch: operations["TodosController.patchTodoPriorityNo"];
  };
  "/openapi": {
    get: operations["OpenapiController.getOpenApi"];
  };
}

export interface components {
  schemas: {
    CategoryBody: {
      category_name: string;
    };
    CategoryPathParams: {
      category_id: number;
    };
    CategoryResponse: {
      category_name: string;
      category_id: number;
      updated_at: string;
    };
    ListCategoryResponse: {
      categories: components["schemas"]["Category"][];
    };
    TodoBody: {
      yarukoto: string;
      category_id?: number;
      kizitu?: string;
      yusendo?: string;
      subcategory_id_list: number[];
      memo?: string;
    };
    TodoPathParams: {
      todo_id: number;
    };
    PatchTodoPriorityNoBody: {
      todos: components["schemas"]["TodoPriorityNo"][];
    };
    TodoPriorityNo: {
      todo_id: number;
      priority_no: number;
    };
    TodoResponse: {
      todo_id: number;
      yarukoto: string;
      priority_no?: number;
      category_id?: number;
      category?: components["schemas"]["Category"];
      kizitu?: string;
      yusendo?: string;
      subcategories: components["schemas"]["Category"][];
      memo?: string;
      updated_at: string;
      done_at?: string | string;
    };
    Category: {
      category_id: number;
      category_name: string;
    };
    ListTodoResponse: {
      todos: components["schemas"]["TodoResponse"][];
    };
  };
}

export interface operations {
  "CategoriesController.getCategories": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ListCategoryResponse"];
        };
      };
    };
  };
  "CategoriesController.postCategory": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
    };
    /** CategoryBody */
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryBody"];
      };
    };
  };
  "CategoriesController.getCategory": {
    parameters: {
      path: {
        category_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
    };
  };
  "CategoriesController.putCategory": {
    parameters: {
      path: {
        category_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
    };
    /** CategoryBody */
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryBody"] & {
          updated_at: string;
        };
      };
    };
  };
  "CategoriesController.deleteCategory": {
    parameters: {
      path: {
        category_id: string;
      };
      query: {
        updated_at: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
    };
  };
  "TodosController.getTodos": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ListTodoResponse"];
        };
      };
    };
  };
  "TodosController.postTodo": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TodoResponse"];
        };
      };
    };
    /** TodoBody */
    requestBody: {
      content: {
        "application/json": components["schemas"]["TodoBody"];
      };
    };
  };
  "TodosController.getTodo": {
    parameters: {
      path: {
        todo_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TodoResponse"];
        };
      };
    };
  };
  "TodosController.putTodo": {
    parameters: {
      path: {
        todo_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TodoResponse"];
        };
      };
    };
    /** TodoBody */
    requestBody: {
      content: {
        "application/json": components["schemas"]["TodoBody"] & {
          updated_at: string;
        };
      };
    };
  };
  "TodosController.deleteTodo": {
    parameters: {
      path: {
        todo_id: string;
      };
      query: {
        updated_at: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TodoResponse"];
        };
      };
    };
  };
  "TodosController.patchTodoDone": {
    parameters: {
      path: {
        todo_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TodoResponse"];
        };
      };
    };
  };
  "TodosController.patchTodoPriorityNo": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ListTodoResponse"];
        };
      };
    };
    /** PatchTodoPriorityNoBody */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchTodoPriorityNoBody"];
      };
    };
  };
  "OpenapiController.getOpenApi": {
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
